### ISSUE TITLE
Issues  while accessing endpoint using cli

### ISSUE THREAD

**Issue by KunalBhoyar** [BigDataIA-Spring2023-Team-09/Assignment_3#12]
Hi, Team while trying to sign in after creating a new user we are getting the below error can you take a look at it to fix it?

**### CLI Command** 
 
PS C:\Users\kb282\OneDrive - Northeastern University\Documents\DAMG_Big_Data\Code Review> python.exe '.\import click.py' -- create_user
Enter username: kbhoyar
Enter password: 
Re-enter password:
Enter email: abc@gmail.com
Enter full name: : kunal
Select subscription tier (free, gold, platinum): gold

### 
**Error Message**

352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ ❱ 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
│                                                                                                  │
│ ╭──────────────────────────── locals ────────────────────────────╮                               │
│ │  idx = 0                                                       │                               │
│ │    s = 'Internal Server Error'                                 │                               │
│ │ self = <json.decoder.JSONDecoder object at 0x0000029D95C80990>

**Comment by LakshmanRaaj** [comment]
This is happening because email already exists and we missed returning proper error message. Please try to register with a new email it will work fine. In the mean time, we will work on that.
