### ISSUE TITLE
Admin treated as a user 

### ISSUE THREAD

**Issue by shu3hamiitkgp** [BigDataIA-Spring2023-Team-09/Assignment_3#17]
When logged in as an admin, it is being treated as a User rather than a system admin. Observations as follows - 

- Access to all modules - GOES, Nexrad, Nexrad plot - this is not required and can be reduced to just dashboard
- Instead of the dashboard showing information for users it's showing API use of the admin. However there is a table with the information of all users but more metrics and charts can be added specific to users like - Users by plans, most trending API module, etc
- The index of the last chart where  API hits by modules is shown, the X-axis ideally should be a date but it seems to indicate some sort of index right now which can be updated

**Comment by Hmittal15** [comment]
Thanks for bringing this up. PFB our response inline:
1. **Access to all modules** - We provided the complete application access for admin to enable them to test/monitor the entire application functionalities at all times.
2. **Dashboard information for users** - Admin is able to see the API call usage by other users as well.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/108916132/225724308-604ed901-578f-4a9b-8228-6b3b0694f7ca.png">

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/108916132/225724397-1f12a45e-fe9c-4a5f-bef8-52dfceac10c3.png">

3. **Chart index** - Duplicate issue (https://github.com/BigDataIA-Spring2023-Team-09/Assignment_3/issues/14)

Thanks for the suggestions, we'll incorporate them moving further.
